"""Standalone HTML tearsheet export."""

from __future__ import annotations

import pandas as pd

_STYLE = """
body { background:#0B0F19; color:#E6E9F0; font-family:-apple-system,'Segoe UI',
       sans-serif; max-width:1100px; margin:32px auto; padding:0 24px; }
h1 { letter-spacing:-.02em; margin-bottom:2px; }
.sub { color:#8B93A7; text-transform:uppercase; letter-spacing:.12em;
       font-size:.75rem; margin-bottom:24px; }
.rule { height:2px; width:64px; background:linear-gradient(90deg,#5B8DEF,
        rgba(91,141,239,0)); margin:10px 0 22px 0; border-radius:2px; }
table { border-collapse:collapse; margin:12px 0 28px 0; width:100%; }
th, td { border:1px solid #232B40; padding:7px 12px; text-align:right;
         font-size:.85rem; }
th { background:#151B2B; color:#8B93A7; text-transform:uppercase;
     font-size:.7rem; letter-spacing:.06em; }
td:first-child, th:first-child { text-align:left; }
h2 { font-size:1.05rem; color:#C9D1E3; margin-top:32px; }
.expr { background:#151B2B; border:1px solid #232B40; border-radius:8px;
        padding:12px 16px; font-family:ui-monospace,Menlo,monospace;
        font-size:.85rem; color:#8FB0FF; }
.footer { color:#5A6478; font-size:.72rem; margin-top:40px; }
"""


def tearsheet_html(
    title: str,
    subtitle: str,
    expression: str,
    metrics: dict,
    figures: list,          # plotly figures, rendered in order
    tables: dict[str, pd.DataFrame] | None = None,
) -> str:
    """Compose a self-contained dark-theme HTML tearsheet (plotly via CDN)."""
    metric_rows = "".join(
        f"<tr><td>{k}</td><td>{v}</td></tr>"
        for k, v in metrics.items())
    figs_html = "".join(
        f.to_html(full_html=False, include_plotlyjs=(i == 0 and "cdn"),
                  default_height=f.layout.height or 420)
        for i, f in enumerate(figures))
    tables_html = ""
    for name, df in (tables or {}).items():
        tables_html += f"<h2>{name}</h2>" + df.to_html(border=0)

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>{_STYLE}</style></head>
<body>
<h1>{title}</h1>
<div class="sub">{subtitle}</div>
<div class="rule"></div>
<div class="expr">{expression}</div>
<h2>Metrics</h2>
<table><tr><th>Metric</th><th>Value</th></tr>{metric_rows}</table>
{figs_html}
{tables_html}
<div class="footer">Generated by Insurance Alpha Lab</div>
</body></html>"""
